refactor: Change PhysicsSolver to PhysicsPackage
GEOS-DEV/GEOS pull request #3245
Opened 2024-07-25 21:00 UTC by rrsettgast

Changes:
- PhysicsSolver -> PhysicsPackage
- SolverBase -> PhysicsPackageBase
-

2024-07-25 21:02 UTC, rrsettgast commented on .github/CODEOWNERS
>  /src/coreComponents/unitTests                         @rrsettgast @corbett5 @wrtobin
```suggestion
/src/coreComponents/unitTests                         @rrsettgast @CusiniM 
```

2024-07-26 13:10 UTC, acitrain requested changes
Hi Randy,

I tried to compile on Pangea 3 (only GEOS, units tests are currently broken due to a previous merge see PR #3244 ), and I found a remaining SolverBase inside 

src/coreComponents/physicsPackages/python/PySolver.cpp : geos::SolverBase * group; it is on line 43

2024-07-26 19:30 UTC, CusiniM approved these changes
It's pretty hard to review but it looks good. I think it would be nice to also collect all kernel files for the flow solvers in a subdir of fluidFlow like we did for the mechanics ones.

2024-07-29 08:34 UTC, acitrain approved these changes
Seems good ! 
Thanks Randy!

2024-08-07 05:21 UTC, castelletto1 commented
Now that we got rid of the concept of `physics solver`, what is the meaning of function `solverStep` in `PhysicsPackageBase.hpp`? Maybe we should rename it.

2024-08-07 21:36 UTC, rrsettgast commented
> Now that we got rid of the concept of `physics solver`, what is the meaning of function `solverStep` in `PhysicsPackageBase.hpp`? Maybe we should rename it.

Good point. Options that I have thought about are:

- `physicsPackageStep()`: pretty self explanatory that it is a "step" for the physics package.
- `timeStep()`: From the codes point of view it is a timestep even if there is no significance on `dt` such as in a quasi-static mechanics step, or equilibrium heat flow.
- `physicsPackageIncrement()`: detach from the "timestep" and just call it an increment. The event manager kind of imposes the timestep, but perhaps the physics package shouldn't care.

2024-11-13 07:13 UTC, closed without merging