Add Pangea4 docker build
GEOS-DEV/GEOS pull request #3248
Opened 2024-07-26 15:34 UTC by Bubusch

# Pangea 4 Docker Build

Adding one new build to emulate Pangea 4 environment.

## Environment Configuration

| Component          | Version            | Installation Method |
|--------------------|--------------------|---------------------|
| RedHat             | 8                  | spack/centos-stream                   |
| GCC                | 12.1               | spack               |
| CMake              | 3.27.9             | spack               |
| Python             | 3.11               | spack               |
| Intel OneAPI MKL   | 2023.2.0           | spack               |
| HPC-X              | 2.17.1             | dl and untar        |

## Run Configuration

| Component          | Status             |
|--------------------|--------------------|
| Hypre              | ON                 |
| Trilinos           | OFF                |
| Host Config        | pangea4-gcc12.1-hpcxompi2.17.1-onemkl2023.2.0.cmake |

## TPLs

- Linked to TPLs' PR [#276](https://github.com/GEOS-DEV/thirdPartyLibs/pull/276)

2024-07-29 04:12 UTC, rrsettgast commented
@Bubusch Does this need the "DO NOT MERGE" flag?

2024-07-29 04:12 UTC, rrsettgast approved these changes

2024-12-06 14:50 UTC, MelReyCG requested changes

2024-12-06 14:50 UTC, MelReyCG commented on host-configs/TotalEnergies/pangea-4/pangea4-base.cmake
> +if (NOT DEFINED GEOS_TPL_DIR)
`DEFINED` will always return `true` here.
```suggestion
if (NOT EXISTS GEOS_TPL_DIR)
```

2024-12-20 14:07 UTC, Bubusch commented on host-configs/TotalEnergies/pangea-4/pangea4-base.cmake
> +if (NOT DEFINED GEOS_TPL_DIR)
indeed, done

2025-02-20 09:27 UTC, Bubusch commented
moved to clean PR with spack

- [TPL-295](https://github.com/GEOS-DEV/thirdPartyLibs/pull/295) Add Pangea4 spack config
- #3561 + [TPL-296](https://github.com/GEOS-DEV/thirdPartyLibs/pull/296) Add Pangea4 CI Job (spack based)

2025-02-20 09:27 UTC, closed without merging