feat: Enable fully coupled mode for CompositionalMultiphaseReservoirPoromechanics and SinglePhaseReservoirPoromechanics
GEOS-DEV/GEOS pull request #3388
Opened 2024-10-04 22:15 UTC by paveltomin

should go after https://github.com/GEOS-DEV/GEOS/pull/3383 and https://github.com/GEOS-DEV/GEOS/pull/3386

- works equivalent to `MultiphasePoromechanicsReservoir` and `SinglePhasePoromechanicsReservoir`, just more convenient to switch between FIM and SEQ within the same solver
- can use the same MGR recipe (order of block is actually the same: mechanics, flow, wells)

2024-10-14 18:50 UTC, paveltomin commented
need review please

2024-10-14 21:31 UTC, CusiniM commented
I am lost. What are these? What s the difference between these and  `MultiphasePoromechanicsReservoir` and `SinglePhasePoromechanicsReservoir` ?

2024-10-14 21:43 UTC, paveltomin commented
> I am lost. What are these? What s the difference between these and `MultiphasePoromechanicsReservoir` and `SinglePhasePoromechanicsReservoir` ?

CompositionalMultiphaseReservoirPoromechanics and SinglePhaseReservoirPoromechanics were created for sequential since MultiphasePoromechanicsReservoir and SinglePhasePoromechanicsReservoir are designed differently: they are flow/mech + wells so when one runs them in sequential they will do flow/mech solve and wells solve iteratively.
CompositionalMultiphaseReservoirPoromechanics and SinglePhaseReservoirPoromechanics were not be able to run in FIM mode which is addressed in this PR.
I know this is confusing and ultimately we should clean this up.

2024-10-29 20:06 UTC, jhuang2601 approved these changes

2024-11-06 23:46 UTC, victorapm approved these changes
Thanks!

2024-11-06 23:46 UTC, victorapm commented on src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
> +  //linearSolverParameters.mgr.separateComponents = true;
This should be needed, but next line can be removed

2024-11-06 23:46 UTC, victorapm commented on src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
> +  //linearSolverParameters.mgr.separateComponents = true;
Same comment as before

2024-11-07 03:16 UTC, CusiniM reviewed
Shouldn't we remove the old solvers though? I would only keep this one with the two options in the same solver.

2024-11-07 03:17 UTC, CusiniM approved these changes

2024-11-07 03:18 UTC, CusiniM requested changes
Actually I would strongly prefer getting rid of `MultiphasePoromechanicsReservoir` and `SinglePhasePoromechanicsReservoir`

2024-11-07 14:47 UTC, paveltomin commented
> Actually I would strongly prefer getting rid of `MultiphasePoromechanicsReservoir` and `SinglePhasePoromechanicsReservoir`

One reason they can be useful is to perform an isolated well solve to precondition the nonlinear system, that's why I am hesitant to remove them

2024-12-13 23:31 UTC, CusiniM approved these changes

2024-12-14 03:07 UTC, merged