Refactor: boundary conditions warning message
GEOS-DEV/GEOS pull request #3417
Opened 2024-10-29 09:46 UTC by arng40

We have a case with CompositionalMultiphaseFVM with wrong **FieldSpecification** declaration initial condtion.
GEOS fails to init boundary conditions and we got a warning message too generic :

2024-10-29 14:20 UTC, paveltomin approved these changes
not sure exposing `CellElement` helps to better understand the issue from user point of view but looks ok

2024-10-29 21:31 UTC, jhuang2601 approved these changes

2024-11-04 13:42 UTC, arng40 commented
@paveltomin I've done a few more changement, now we centralize messages in `FlowSolverBase`, as some messages are repeated between `ReactiveCompositionalMultiphaseOBL` and `CompositionalMultiphaseBase`

2024-11-04 14:43 UTC, paveltomin approved these changes

2024-11-05 14:06 UTC, MelReyCG requested changes

2024-11-05 14:06 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
> +    static string generateMessage( string_view baseMessage,
As you want a static class here, please set the constructor private.

2024-11-05 14:06 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
> +string FlowSolverBase::BCMessage::inconsistency( int componentIndex, string_view componentName,
Can we name this one `notAppliedOnRegion`?

2024-11-05 14:06 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
> +  return GEOS_FMT( "{} Check if you have added or applied the appropriate fields to "
Prefer to add the layout details (like `\n`) where you **actually set the layout**.
Imagine if you finally want to put the `baseMessage` at the bottom of this one, you will have to remove the `\n` at 7 lines instead of only one.

2024-11-05 14:06 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
> +}
Can we have the actual composition name?

```suggestion
string FlowSolverBase::BCMessage::conflictingComposition( string_view compName,
                                                          string_view regionName, string_view subRegionName,
                                                          string_view setName, string_view fieldName )
{
  return generateMessage( GEOS_FMT( "Conflicting composition[{}] boundary conditions on set {}/{}/{}\n",
                                    compName, regionName, subRegionName, setName ), fieldName, setName );
}
```

Same question for `invalidComponentIndex()` and `inconsistency()`.

2024-11-05 14:06 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
> +}
And we miss a space in `composition[{}]` (also in `inconsistency()`)

2024-11-05 14:20 UTC, arng40 commented on src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
> +}
for invalidComponentIndex() cause it's invalid but for conflicComposition (not inconsistency()) yes

2024-11-05 16:36 UTC, CusiniM commented
can we remove the Ci labels until it's closer to being ready?

2024-11-05 16:38 UTC, MelReyCG approved these changes

2024-11-05 16:39 UTC, MelReyCG commented
This PR seems to be ready now 👍

2024-11-06 19:32 UTC, merged