test: Add unit tests for RTType.hpp
GEOS-DEV/GEOS pull request #3452
Opened 2024-11-18 22:37 UTC by OmarDuran

Introduces unit test for `RTTypes.hpp`. The motivation is to test a failing dynamic cast with reference in apple clang 16.0.0 when `NEW_TYPE==EXISTING_TYPE` (see [NEW_TYPE dynamicCast( EXISTING_TYPE & val )](https://github.com/GEOS-DEV/GEOS/blob/e9492b5354039ac641c27996b65b502d006e6883/src/coreComponents/codingUtilities/RTTypes.hpp#L62)).

Other functions and structures are being tested  `RTTypes.hpp` to augment the test coverage.

2024-11-19 19:49 UTC, CusiniM commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +    m_group( "root", m_node ),
do you need these 2?

2024-11-19 19:52 UTC, CusiniM commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +    m_group( "root", m_node ),
I guess the wrapper constructor nees a group... But what's the conduit node for?

2024-11-19 19:55 UTC, CusiniM commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +    m_group( "root", m_node ),
ah... you need to make a Group.. okay I was hoping we could avoid that include.

2025-10-30 16:26 UTC, herve-gross commented
Should this PR be pushed?

2025-11-13 02:49 UTC, OmarDuran commented on src/coreComponents/codingUtilities/tests/CMakeLists.txt
> +)
Deleted.

2025-11-13 02:56 UTC, OmarDuran commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +}
fixed.

2025-11-13 02:56 UTC, OmarDuran commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +}
fixed.

2025-11-13 03:12 UTC, OmarDuran commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +    << "Unexpected brief name: " << briefEnum;
After accepting one of Copilot’s suggestions, the structure of the code no longer made any sense. It’s now fixed.

2025-12-16 16:19 UTC, MelReyCG requested changes

2025-12-16 16:19 UTC, MelReyCG commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +#include "dataRepository/Wrapper.hpp"
The test must be relocated because of circular dependancy.
I advise `src/coreComponents/dataRepository`.

2025-12-16 16:19 UTC, MelReyCG commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +  EXPECT_FALSE( std::regex_match( std::string( "{1,2,3,4}" ), re ) ); // Not a 2d array pattern
Why not adding those formatting tests in the existing `testXmlWrapper.cpp`?

At least, can you specify the role of the two files (`testRTTypes.cpp` and `testXmlWrapper.cpp`) in a doxygen file header, so we know what needs to be tested in each one?

2025-12-16 21:04 UTC, OmarDuran commented on src/coreComponents/codingUtilities/tests/testRTTypes.cpp
> +  EXPECT_FALSE( std::regex_match( std::string( "{1,2,3,4}" ), re ) ); // Not a 2d array pattern
This is a good point, thank you.

2026-05-12 20:27 UTC, OmarDuran commented
I am closing this PR due to current resource constraints.

2026-05-12 20:27 UTC, closed without merging