Feature/dudes/log level doc package
GEOS-DEV/GEOS pull request #3494
Opened 2024-12-17 14:30 UTC by arng40

2024-12-19 12:25 UTC, acitrain approved these changes

2025-01-14 13:18 UTC, MelReyCG requested changes

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/events/tasks/TaskBase.hpp
> +#include "events/LogLevelsInfo.hpp"
-> cpp

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/events/LogLevelsInfo.hpp
> +  static constexpr std::string_view getDescription() { return "Informations on events executed"; }
```suggestion
  static constexpr std::string_view getDescription() { return "Informations on events execution"; }
```

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/fileIO/LogLevelsInfo.hpp
> +};
Taking the description into account, name should be something like `HDF5Writing` (or you can update the description to be more generic)

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/fileIO/Outputs/VTKOutput.cpp
> +    GEOS_LOG_LEVEL_INFO( logInfo::OutputEvents, GEOS_FMT( "{}: writing {} at time {} s (cycle number {})", getName(), m_fieldNames, time_n + dt, cycleNumber ));
long line (please verify all your PR, it is not the only one)

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/events/LogLevelsInfo.hpp
> +};
Should located in `fileIO` and may be renamed `DataCollectorInitialization`.

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/events/tasks/TaskBase.cpp
> +  addLogLevel< logInfo::Initialization >();
unused, isn't it ?

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
> +  GEOS_LOG_LEVEL_INFO_BY_RANK( logInfo::Initialization, GEOS_FMT( "TimeHistory: '{}' initializing data collectors.", this->getName() ) );
Can we now remove the old macros?
- `GEOS_LOG_LEVEL_FN()`
- `GEOS_LOG_LEVEL()`
- `GEOS_LOG_LEVEL_RANK_0()`
- `GEOS_LOG_LEVEL_BY_RANK()`

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> -struct Initialization
You changed the level of this `Initialization` one! (1->3)
You should keep it here and may rename it `SolverInitialization` to emphase the "theme" (or a namespace may be good here, as seen in `geos::fields`).

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/mesh/generators/WellGeneratorBase.cpp
> +  addLogLevel< logInfo::VTKSteps >();
unused?

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/mesh/generators/WellGeneratorBase.hpp
> +#include "mesh/LogLevelsInfo.hpp"
->cpp... if used.

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/fileIO/Outputs/ChomboIO.cpp
> +    GEOS_LOG_LEVEL_INFO( logInfo::OutputEvents, "Initializing chombo coupling" );
I would use your `logInfo::Initialization` here

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/fileIO/LogLevelsInfo.hpp
> +  static constexpr int getMinLogLevel() { return 1; }
2

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/wells/LogLevelsInfo.hpp
> +struct Crossflow
COLLISION!
delete the other one

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/contact/ContactSolverBase.cpp
> +#include "physicsSolvers/contact/LogLevelsInfo.hpp"
Why?

2025-01-14 13:18 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/wells/LogLevelsInfo.hpp
> +  static constexpr int getMinLogLevel() { return 2; }
1

2025-01-17 13:19 UTC, arng40 commented on src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
> +  GEOS_LOG_LEVEL_INFO_BY_RANK( logInfo::Initialization, GEOS_FMT( "TimeHistory: '{}' initializing data collectors.", this->getName() ) );
I can't remove GEOS_LOG_LEVEL_BY_RANK, because it's used by `HDFHistoryIO`and the mechanism of adding logLevel is located on `Group.hpp` but the 3 others I remove them

2025-01-21 08:31 UTC, MelReyCG approved these changes

2025-01-22 17:30 UTC, rrsettgast approved these changes
@arng40 
Just a couple of typos. 

Also, could you create a "log level" section in the documentation to give an example of usage for the revised approach to log levels?

2025-01-22 17:30 UTC, rrsettgast commented on src/coreComponents/events/LogLevelsInfo.hpp
> + * Copyright (c) 2019-     GEOSX Contributors
```suggestion
 * Copyright (c) 2016-2024 Lawrence Livermore National Security LLC
 * Copyright (c) 2018-2024 TotalEnergies
 * Copyright (c) 2018-2024 The Board of Trustees of the Leland Stanford Junior University
 * Copyright (c) 2023-2024 Chevron
 * Copyright (c) 2019-     GEOS/GEOSX Contributors
 * All rights reserved
```

2025-01-22 17:30 UTC, rrsettgast commented on src/coreComponents/fileIO/LogLevelsInfo.hpp
> + * Copyright (c) 2019-     GEOSX Contributors
```suggestion
 * Copyright (c) 2016-2024 Lawrence Livermore National Security LLC
 * Copyright (c) 2018-2024 TotalEnergies
 * Copyright (c) 2018-2024 The Board of Trustees of the Leland Stanford Junior University
 * Copyright (c) 2023-2024 Chevron
 * Copyright (c) 2019-     GEOS/GEOSX Contributors
 * All rights reserved
```

2025-01-22 17:30 UTC, rrsettgast commented on src/coreComponents/mesh/LogLevelsInfo.hpp
> + * Copyright (c) 2019-     GEOSX Contributors
```suggestion
 * Copyright (c) 2016-2024 Lawrence Livermore National Security LLC
 * Copyright (c) 2018-2024 TotalEnergies
 * Copyright (c) 2018-2024 The Board of Trustees of the Leland Stanford Junior University
 * Copyright (c) 2023-2024 Chevron
 * Copyright (c) 2019-     GEOS/GEOSX Contributors
 * All rights reserved```

2025-01-22 20:22 UTC, CusiniM commented on src/coreComponents/events/LogLevelsInfo.hpp
> +  static constexpr int getMinLogLevel() { return 1; }
at some point instead of hadcoding these values we could define in a central location something like:


````c++
enum class LogLevel : integer
{
  Minimal,
  Normal,
  Verbose
````
and then use it throughout the code.

2025-01-22 20:22 UTC, CusiniM commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +};
shouldn't this go in `FlowSolvers`?

2025-01-22 20:22 UTC, CusiniM commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +};
same for this

2025-01-22 20:22 UTC, CusiniM commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +};
move to SurfaceGenerator?

2025-01-22 20:22 UTC, CusiniM commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +struct StencilConnection
would expect this in Flow too.

2025-01-22 20:22 UTC, CusiniM commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +struct WellValidity
and I would expect these to be define in the Well solvers folder.

2025-01-23 01:42 UTC, rrsettgast commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +};
It seems that several subfolder `LogLevelsInfo.hpp` files were removed and consolidated at a higher level. I am not sure this is what we would want? @arng40 What is the argument for the consolidation?

2025-01-23 09:26 UTC, arng40 commented
@rrsettgast @CusiniM 
Concerning the files that being moved at a higher level, I was divided between keep things simple by putting the log levels at a higher level or group the log levels and set them to correct location.
With your comments I'll go for 2nd option

2025-01-23 14:21 UTC, arng40 commented on src/coreComponents/events/LogLevelsInfo.hpp
> +  static constexpr int getMinLogLevel() { return 1; }
Hardcoded value will be removed with the Logger with @MelReyCG working on it, here a preview :
/// @brief Enumerate the logging levels from the most importants messages to the one that contain the more details.
enum class LogLevel : int16_t
{
  Silent = -1,    // Useful as a globalLogLevel for silencing the logger. shouldn't be used as a message level.
  Important = 0,  // Application level messages (help, almost blocking warnings, application informations & phases)
  Progress = 1,   // Time step attempts, newton loop progress of Solver objects
  Detailed = 2,   // More detailed info and stats that affect progress, e.g. residual norms.
  Trace = 3,      // This is intended as a user-level debugging tool. detailed info trace what each component is
                  // doing. e.g. a line for every part of the assembly process, every boundary condition that's being
                  // applied by a physics solver, etc.
  Debug = 4,      // Information that are only relevant for a developper in a debugging context.
  DebugTrace = 5, // This level is useful to have deeper debugging information (which can be potencially heavy to log).
};

2025-01-24 08:39 UTC, arng40 commented on src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
> +};
Concerning the files that being moved at a higher level, I was divided between keep things simple by putting the log levels at a higher level or group the log levels and set them to correct location.
With your comments I'll go for 2nd option

2025-01-29 16:03 UTC, MelReyCG requested changes
[https://geosx-geosx--3494.com.readthedocs.build/en/3494/docs/sphinx/datastructure/CompleteXMLSchema.html#input-schema-definitions](https://geosx-geosx--3494.com.readthedocs.build/en/3494/docs/sphinx/datastructure/CompleteXMLSchema.html#input-schema-definitions)
There still are some undocumented `logLevel` parameters (like `Aquifer`). If they do not output any message in the log, they should not appear.

2025-01-29 16:08 UTC, MelReyCG requested changes
In LogLevelsRegistry.cpp, 
```
  description << "Sets the level of information to write in the standard output (the console typically).\n"
                 "Level 0 outputs no specific information for this solver. Higher levels require more outputs.";
```
This description can be improved:
- properly mention that the levels adds up with the lower levels,
- as it is written for any `Group`, even those that are unrelated to solvers, you cannot relate to any "solver" concept.

2025-02-04 13:05 UTC, arng40 commented
https://github.com/GEOS-DEV/GEOS/pull/3494/commits/036234d7b8170bc88b59fca77cc5e750c1b1f433
@rrsettgast @matteofrigo5 
I commented a line where a log could possibly be executed on GPU, and with the log level implementation the code is no longer compatible.

2025-02-06 14:37 UTC, arng40 commented
@rrsettgast I manually checked the TestsResults folder with `process_tests_failures.py` with only 'logLevel' as exclusion string and the script output : `No unfiltered differences were found.`

2025-02-10 13:57 UTC, MelReyCG commented on host-configs/TOTAL/pangea4-base.cmake
> +set(GEOS_TPL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../thirdPartyLibs/install-pangea4-gcc12.1-hpcxompi2.17.1-onemkl2023.2.0-release" CACHE PATH "" FORCE)
Out of PR scope.

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/events/LogLevelsInfo.hpp
> + * Copyright (c) 2019-     GEOSX Contributors
@arng40 still not adressed?

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/constitutive/CMakeLists.txt
> +     fluid/multifluid/CO2Brine/LogLevelsInfo.hpp
Apply lexicographic sorting for `CMakeLists`, especially for those that are that large (there are extensions for that).
Do that for all your new CMakeLists entries.

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/events/tasks/TaskBase.cpp
> +#include "events/LogLevelsInfo.hpp"
unused, please revert this file and TaskBase.hpp as you modified their formatting

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/events/EventManager.cpp
> +      GEOS_LOG_LEVEL_RANK_0( logInfo::SubEventExecution,
I think you may have mismatched ``EventExecution`` and ``SubEventExecution``

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/mesh/generators/WellGeneratorBase.cpp
> +  addLogLevel< logInfo::PerforationTable >();
Where are they used?

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
> +  addLogLevel< logInfo::Rates >();
Is `logInfo::Rates` ever used?

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
> +#include "physicsSolvers/fluidFlow/LogLevelsInfo.hpp"
That's why we should prefer lexicographical sorting for CMakeLists & headers

2025-02-10 13:57 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/PhysicsSolverBase.cpp
>    addLogLevel< logInfo::Timers >();
All those `logInfo` doesn't apply to **all** `PhysicsSolverBase` children, the generated documentation will be wrong for some of them.

The thing that is hard to track is that inheritance can break your system (producing double entries): with your current system, we cannot add a `logInfo` twice (in parent class and child class), which force us to not call `addLogLevel()` in each class that use a given `logInfo`.

It would be easier to maintain a good documentation if `LogLevelsRegistry::addEntry()` would verify if a description already exist in the list, allowing us **to call the `addLogLevel()` in each class using it**, simplifying whole `logInfo` usage to _"if I use it, I have to declare it"_, and simplifying any polymorphism implications.

2025-02-13 14:07 UTC, arng40 commented on src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
> +  addLogLevel< logInfo::Rates >();
no

2025-02-13 14:07 UTC, arng40 commented on src/coreComponents/mesh/generators/WellGeneratorBase.cpp
> +  addLogLevel< logInfo::PerforationTable >();
added some check with logInfo

2025-02-13 16:40 UTC, MelReyCG reviewed
Just noticing that *someone* disabled loglevels for stats (which are now in tables, like at src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp:515)

2025-02-14 09:10 UTC, MelReyCG commented on src/coreComponents/mesh/generators/WellGeneratorBase.cpp
> +  addLogLevel< logInfo::PerforationTable >();
make sure you use `isLogLevelActive< logInfo::X >()`

2025-02-14 09:21 UTC, MelReyCG commented on src/coreComponents/events/EventManager.cpp
> +      GEOS_LOG_LEVEL_RANK_0( logInfo::SubEventExecution,
Seen your last version, is `logInfo::SubEventExecution` useful?

2025-02-14 09:35 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
> +  addLogLevel< logInfo::Rates >();
As now, the rates are "hidden" in `SurfaceCondition` log info, we may prefer another term to guide the user in the surface-condition & rate logging.
What about `FluxConditions`? `Flux`? Something else?
We may group BHP into this logInfo too.
You need user feedback to states on that.

2025-02-14 09:37 UTC, MelReyCG requested changes
Still some issues to adress.

2025-02-14 10:16 UTC, arng40 commented on src/coreComponents/events/EventManager.cpp
> +      GEOS_LOG_LEVEL_RANK_0( logInfo::SubEventExecution,
i switch them

2025-02-17 13:32 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
> +      GEOS_LOG_LEVEL_RANK_0( logInfo::DetailedStatisticsInformation,
I think `DetailedStatisticsInformation` is bound to `Statistics` information: you cannot show `Statistics` without `DetailedStatisticsInformation`, and `DetailedStatisticsInformation` has no sense without `Statistics`.
I would just merge `DetailedStatisticsInformation` to keep only `Statistics`.

2025-02-17 13:36 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/PhysicsSolverBase.cpp
>    addLogLevel< logInfo::Timers >();
Well done in your last version. Nice thing that you fixed the "double entries" bug.

2025-02-17 13:51 UTC, MelReyCG requested changes

2025-02-17 13:51 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/NonlinearSolverParameters.cpp
> +  addLogLevel< logInfo::Convergence >();
I think you may have forgotten `logInfo::Timestep` here

2025-02-17 13:51 UTC, MelReyCG commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
> +                                       getName(), regionNames[i] ) );
I think `DetailedStatisticsInformation` is bound to `Statistics` information: you cannot show `Statistics` without `DetailedStatisticsInformation`, and `DetailedStatisticsInformation` has no sense without `Statistics`.
I would just merge `DetailedStatisticsInformation` to keep only `Statistics`.

2025-02-27 08:06 UTC, MelReyCG approved these changes

2025-03-02 23:53 UTC, CusiniM commented on src/coreComponents/constitutiveDrivers/fluid/multiFluid/LogLevelsInfo.hpp
> + * This file contains common log level informations for physics solvers
```suggestion
 * This file contains common log level informations for physics solvers
```


this does not seem to be for physics solvers but for constitutive models

2025-03-03 00:00 UTC, CusiniM commented on src/coreComponents/physicsSolvers/wavePropagation/shared/WaveSolverBase.cpp
> +    GEOS_LOG_LEVEL_RANK_0( logInfo::DASType, "Modeling linear DAS data is activated" );
How is this working since you seem to have deleted this Macro?

2025-03-03 00:05 UTC, CusiniM commented on src/coreComponents/constitutive/fluid/multifluid/CO2Brine/LogLevelsInfo.hpp
I don't understand this move...

2025-03-03 00:08 UTC, CusiniM commented on src/coreComponents/physicsSolvers/wavePropagation/shared/WaveSolverBase.cpp
> +    GEOS_LOG_LEVEL_RANK_0( logInfo::DASType, "Modeling linear DAS data is activated" );
nevermind, I found the new one. I don't know why the search is not working properly.

2025-03-03 00:08 UTC, CusiniM approved these changes

2025-03-03 08:41 UTC, arng40 commented on src/coreComponents/constitutiveDrivers/fluid/multiFluid/LogLevelsInfo.hpp
> + * This file contains common log level informations for physics solvers
yes and there are some of these at other location

2025-03-03 09:31 UTC, arng40 commented on src/coreComponents/constitutive/fluid/multifluid/CO2Brine/LogLevelsInfo.hpp
Which move are we talking ? I don't get it

2025-03-09 21:37 UTC, rrsettgast approved these changes

2025-03-09 21:37 UTC, rrsettgast commented on src/coreComponents/constitutive/fluid/multifluid/LogLevelsInfo.hpp
> +#define GEOS_CONSTITUTIVE_FLUID_MULTIFLUID
This should be the name of the file??

2025-03-09 21:37 UTC, rrsettgast commented on src/coreComponents/constitutive/fluid/multifluid/CO2Brine/LogLevelsInfo.hpp
> +#define GEOS_CONSTITUTIVE_FLUID_MULTIFLUID_CO2BRINE_HPP
need filename

2025-03-09 21:37 UTC, rrsettgast commented on src/coreComponents/mesh/LogLevelsInfo.hpp
> +
wrong path

2025-03-12 14:03 UTC, MelReyCG approved these changes

2025-03-18 19:24 UTC, merged